name: hello-world
'on': push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: extract git commit data
        uses: lespinasse/git-commit-date-action@v1.x
      - name: Update author information
        uses: 'echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR'
      - name: Raise PR
        id: demo-1
        uses: peter-evans/create-pull-request@v3
        with:
          branch: auto-pr-branch
          base: main
          title: demo for auto pr
          committer: >-
            ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL
            }}>
          author: >-
            ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL
            }}>
          body: This is to show automatic PR creation
          token: '${{ secrets.GITHUB_TOKEN }}'
          delete-branch: true
